### ISSUE TITLE
Week 2 Presentation Review Ticket

### ISSUE THREAD

**Issue by parkjessie** [parkjessie/LAJ#10]
- [ ] Big Idea, Sponsor, Hosting Plan, GitHub license
- [ ] WireFrames or Web Page mock ups
- [ ] Key Workflow or actions within site. See recent Tweet
- [ ] Data and any Data Privacy or Security needed.  For instance between Admin and Users of system.

**Comment by jm1021** [comment]
Attendance COVID tracing Ms Rowe is sponsor.   

Create program that can pull information from synergy, see if they are absent, and help make a google doc.

Deployment on AWS, GPL v3 website.     

Teacher to enter information of students around sick student.  

There seems to be restrictions in ID about access to information.   Perhaps we should look at what Ms Rowe is using.   Mort says this could be big obstactle.

Question on availability:   Only available to administrators.

Question about asking about email others.   Intentions is to email parents.

Teacher suggest need User Experience diagram to discuss work flow.
